#!/bin/bash

# This script helps with the management of simple
# cheat sheets that you edit and view from the terminal.


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if ! [ -d "${SCRIPT_DIR}/cheats" ]; then
  mkdir "${SCRIPT_DIR}/cheats"
fi

SHEET_FILES=( `ls ${SCRIPT_DIR}/cheats/*.txt 2>/dev/null` )
SHEETS=()

for sheet in "${SHEET_FILES[@]}"; do
  SHEETS+=("$(basename $sheet .txt)")
done


print_available_sheets() {
  echo "Available cheat sheets:"

  if [ ${#SHEETS[@]} -eq 0 ]; then
    echo "  None"
    return 0
  fi

  for sheet in "${SHEETS[@]}"; do
    echo " - $sheet"
  done
}

print_usage() {
  echo "Usage: cheat [options] <cheat sheet>"
  echo "With no options, the cheat sheet will just be displayed."
  echo "Options:"
  echo "  -n | --new <cheat sheet>"
  echo "    Create new cheat sheet and enter edit mode"
  echo "  -e | --edit <cheat sheet>"
  echo "    Edit the source cheat sheet"
  echo "  -l | --list"
  echo "    List available cheat sheets"
  echo "  -h | --help"
  echo "    Print usage"
  echo "  --rm <cheat sheet>"
  echo "    Delete the cheat sheet"
  echo ""
  print_available_sheets
  echo ""
}

sheet_exists() {
  local match="$1"
  for s in "${SHEETS[@]}"; do [[ "$s" == "$match" ]] && return 0; done
  return 1
}

check_sheet_exists() {
  local sheet="$1"
  if ! sheet_exists "$sheet" ; then
    echo "Cheat sheet '$sheet' does not exists"
    print_available_sheets
    exit 1
  fi
}

edit_file() {
  local sheet="$1"
  if [ -z "$sheet" ]; then
    echo "You must provide a sheet to edit."
    print_usage
    exit 1
  else
    nano "${SCRIPT_DIR}/cheats/${sheet}.txt"
  fi
}

create_new_file() {
  local new_sheet="$1"

  if [ -z "$new_sheet" ]; then
    echo "You must specify a new cheat sheet to create."
    print_usage
    exit 1
  fi

  if sheet_exists "$new_sheet" ; then
    read -p "Cheat sheet '$new_sheet' exists. Do you want to overwrite it [y/N]? "
    if [ "$REPLY" != "y" ]; then
      exit 0
    fi
  fi

  edit_file "$new_sheet"
}

delete_sheet() {
  local sheet="$1"

  read -p "Are you sure you want to delete '$sheet' [y/N]? "
  if [ "$REPLY" == "y" ]; then
    rm "${SCRIPT_DIR}/cheats/${sheet}.txt"
  fi
}


while [ -n "$1" ]; do
  case "$1" in
    -n | --new  )
      create_new_file "$2"
      exit 0
      ;;
    -e | --edit )
      check_sheet_exists "$2"
      edit_file "$2"
      exit 0
      ;;
    -l | --list )
      print_available_sheets
      exit 0
      ;;
    -h | --help )
      print_usage
      exit 0
      ;;
    --rm )
      check_sheet_exists "$2"
      delete_sheet "$2"
      exit 0
      ;;
    * )
      check_sheet_exists "$1"
      cat "${SCRIPT_DIR}/cheats/${1}.txt"
      exit 0
      ;;
  esac
  shift
done

